apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        all:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "nixvarghese03/devsecop-frontend:*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE08Aej33Nmmub2+HshaBiuLIiqMhV
                NrIHxyJeZdA1pAjpO4NrIu6a9aBbp+8rnp/7xWFDpTAPGcqt5sZAVG1s1w==
                -----END PUBLIC KEY-----
